// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetDocMessage } from "./GetDocMessage";
import type { JoinRoomMessage } from "./JoinRoomMessage";
import type { QueryAIMessage } from "./QueryAIMessage";
import type { UpdateDocMessage } from "./UpdateDocMessage";
import type { UpdateTmpStateMessage } from "./UpdateTmpStateMessage";

export type ClientMessage = { "type": "join_room", "data": JoinRoomMessage } | { "type": "update_doc", "data": UpdateDocMessage } | { "type": "update_tmp_state", "data": UpdateTmpStateMessage } | { "type": "get_doc", "data": GetDocMessage } | { "type": "query_a_i", "data": QueryAIMessage };
