// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIQueries } from "./AIQueries";

export type QueryAIMessage = { verb: AIQueries, parameters: string | null, };
